defaults: &defaults
  adapter: postgresql
  host: "<%= ENV.fetch('DB_HOST', 'localhost') %>"
  username: "<%= ENV.fetch('DB_USERNAME', 'postgres') %>"
  password: "<%= ENV.fetch('DB_PASSWORD', 'postgres') %>"
  encoding: unicode
  pool: 100

development:
  <<: *defaults
  database: "<%= ENV.fetch('APP_MODE', 'property') %>_development"

test:
  <<: *defaults
  database: property_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *defaults
  database: "<%= ENV.fetch('DB_NAME', 'property_development') %>"
